pipeline{
    agent any
    environment{
        DOCKER_TAG = getDockerTag()
    }
    stages{
        stage('Build Docker Image') {
            steps{
                sh "docker build . -t bharat/nodeapp:${DOCKER_TAG} "
            }
        }
        stage('DockerHub push') {
            steps{
                withCredentials([string(credentialsId: 'docker-hub', variable: 'dockerHubpwd')]) {
                     sh "docker login -u bharat -p ${dockerHubpwd}"
                     sh "docker push bharat/nodeapp:${DOCKER_TAG}"
                }
            }
        }
        stage('Docker Deploy Devserver') {
            steps{
                echo "Deploying to dev server"
                
            }
        }
    }
}

def getDockerTag(){
    def tag  = sh script: 'git rev-parse HEAD', returnStdout: true
    return tag
}
